title: Christopher Baim
logo: "/assets/CB.png?raw=true"
description:
  Python developer
  <br><br>
  MSc in Neuroscience
  <br><br>
  <a href="https://www.linkedin.com/in/chrisbaim/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
icon: flavicon.ico